collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4412578
  lightness: 0.5663324
  brandStrength: 0.1290323
  brandColors:
    - '#83C8B5'
    - '#F0774C'
    - '#FFFBFA'
    - '#FFAB89'
  rhythmicContrast: 0.7467701
typography_spectrum: 0.7795699
layout_spectrum: 0.9946237
name: 8fjell
