layout_spectrum: 0.06453342
typography_spectrum: 0.06176626
color:
  saturation: 0.4412578
  lightness: 0.5663324
  brandStrength: 0.2966567
  rhythmicContrast: 0.7467701
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: 8fjell
